max_epochs: 1
gpus: 1 
n: 2
batch_size: 128
segments: 2
layer_type: continuous2d 
train_fraction: 1.0
gradient_clip_val: 0.0
num_workers: 20
learning_rate: 1.0e-3
periodicity: null
optimizer: lion

# [-1 to 1]
scale: 2

# Currently only "resnets" transformed from torchvision
# have been implemented.
model_name: resnet10

# cross_entropy or mse
loss: cross_entropy

# resize the input and output channels. new_channel = int(old_channels/rescale_planes)
rescale_planes: 1

# Whether to average the output by the number of inputs.  Important for polynomials.
rescale_output: False

# Train layer by layer or not
layer_by_layer: False

# Number of training epochs for a given layer before moving onto the next.
epochs_per_layer: 10

num_classes: 100

# Whether to clamp weights or not
clamp_weights: False